source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.3.0"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "webrick"
  gem "jekyll-pagebreak", "0.9.2"
end
